### PR TITLE
Fix the edge-to-edge implementation of the search box

### PR DESCRIPTION
**Pull request by yaraki**
Screenshot_1676282615

### CODE REVIEW

**Comment by marcelpinto** [comment]
There seems to be a space at the start of the bar but not at the end. Can you make sure that's aligned? Either by taking full screen or using the same space at the end

**Comment by yaraki** [comment]
I wrapped it with TopAppBar because it handles window insets for us. But it adds padding at the start and it can't be removed.

1. Add the same padding at the end.
2. Handle the window insets on our side.

I feel like doing 2. WDYT?

**Comment by yaraki** [comment]
I did 2 and this is how it looks now.

Screenshot_1676284233

**Review by marcelpinto — APPROVED** [review]
Yup, I prefer the full width mode. Thanks

**Pull request merged**
